version: '2.0'
services:
  front:
    image: scrapf
    build: front
    ports:
     - "1234:1234"
    volumes:
     - "./front:/app"
  back:
    image: scraps
    build: api
    ports:
     - "8080:8080"
